// <auto-generated />
using System;
using MetalixDemoErp.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetalixDemoErp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230618173110_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetalixDemoErp.Entitiy.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MetalixDemoErp.Entitiy.DangilNo", b =>
                {
                    b.Property<int>("DangilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangilId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("Dangilno")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DangilId");

                    b.HasIndex("CompanyId");

                    b.ToTable("DangilNoes");
                });

            modelBuilder.Entity("MetalixDemoErp.Entitiy.DangilNo", b =>
                {
                    b.HasOne("MetalixDemoErp.Entitiy.Company", null)
                        .WithMany("DangilNo")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("MetalixDemoErp.Entitiy.Company", b =>
                {
                    b.Navigation("DangilNo");
                });
#pragma warning restore 612, 618
        }
    }
}
